version: 2.1

executors:
  puppeteer-play:
    docker:
      - image: circleci/node:10
    working_directory: ~/Puppeteer-Play

jobs:

  test:
    executor: puppeteer-play
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Check code quality
          command: docker-compose exec default yarn lint
      # - run:
      #     name: Runs ui tests
      #     command: docker-compose exec default yarn ui
      # - run:
      #     name: Runs api tests
      #     command: docker-compose exec default yarn api

workflows:
  version: 2
  e2e-testing:
    jobs:
      - test
